apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  completions: 10  # Run 3 tasks
  parallelism: 2  # Run 2 tasks at a time
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["echo", "Processing Task"]
      restartPolicy: Never

